version: 2
jobs:
  build:
    context: nova-assets
    working_directory: ~/workdir
    machine: true
    steps:
      - run:
          name: Clone repository
          command: |
            git clone https://${DOCS_GITHUB_TOKEN}@github.com/solarfrantz/${CIRCLE_PROJECT_REPONAME}.git .
      - run:
          name: Download resources
          command: |
            cd icons
            rm -f *
            git checkout package.json
            
            wget -q https://i.icomoon.io/public/temp/a976e5f24b/UntitledProject/selection-svg.json
            git add .
      - run:
          name: NPM pack
          command: |
            cd icons
            npm pack # => generic-icons-1.0.0.tgz

            # authenticated with github
            echo '//npm.pkg.github.com/:_authToken=${DOCS_GITHUB_TOKEN}' > .npmrc
            # npm login --scope=@test-assets-3984 --registry=https://npm.pkg.github.com
            
      - deploy:
          name: Trigger deployment
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "francisc.ungureanu@solarwinds.com"
            git config user.name "solarfrantz"
            #git commit --allow-empty -am "Trigger deployment"
            # Push quietly to prevent showing the token in log
            # git push -q https://${DOCS_GITHUB_TOKEN}@github.com/solarfrantz/${CIRCLE_PROJECT_REPONAME}.git ${CIRCLE_BRANCH}
