version: 2
jobs:
  build:
    context: nova-assets
    working_directory: ~/workdir
    machine: true
    steps:

      - run:
          name: Clone repository
          command: |
            git clone ${CIRCLE_REPOSITORY_URL} .

      - run:
          name: Download resources
          working_directory: ~/workdir/icons
          command: |
            # remove any previous downloaded resources
            rm -f *

            # keep certain files to be available in the npm package
            git checkout package.json README.md
            
            # list of files to be downloaded
            files=(
                # SVG
                "symbol-defs.svg"

                # web fonts
                # "icomoon.eot"
                # "icomoon.ttf"
                # "icomoon.woff"

                "selection.json"

                "style-svg.css"
                # "style.css"
                "svgxuse.js"
            )
             
            # Print array values in  lines
            for filename in ${files[*]}; do
                echo "Downloading ${ICOMOON_URL}/${filename}"
                wget -q ${ICOMOON_URL}/$filename
            done            
            
      - run:
          name: Detecting resource changes
          working_directory: ~/workdir/icons
          command: |
            # checking for any changes
            GIT_CHANGES=`git status --porcelain --untracked-files=no | wc -l`
            echo "Found ${GIT_CHANGES} change(s)"

            if [ $GIT_CHANGES -eq 0 ] ; then
                echo "No resources changed"
                circleci-agent step halt
            else
                echo "Found the following $GIT_CHANGES change(s)"
                git status
                
                # increment package version
                npm version patch

                # prepare for commiting all downloaded resources that have changed
                git add .
            fi

      - run:
          name: npm pack & publish
          working_directory: ~/workdir/icons
          command: |
            npm pack

            # authenticate with GitHub personal access token
            echo "//npm.pkg.github.com/:_authToken=${GITHUB_PERSONAL_TOKEN}" > .npmrc
            
            npm publish

      - deploy:
          name: Trigger deployment
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "${GITHUB_EMAIL}"
            git config user.name "${GITHUB_USER}"
            git commit -m "Trigger deployment"

            # Push quietly to prevent showing the token in log
            git push -q https://${DOCS_GITHUB_TOKEN}@github.com/solarfrantz/${CIRCLE_PROJECT_REPONAME}.git ${CIRCLE_BRANCH}

      - run:
          name: Cleanup
          working_directory: ~/workdir/icons
          command: |
            rm *.tgz
            rm .npmrc

      - store_artifacts:
          path: ~/workdir/icons
