version: 2
jobs:
  build:
    context: nova-assets
    working_directory: ~/workdir
    machine: true
    steps:
    
      - run:
          name: Clone repository
          command: |
            git clone https://${DOCS_GITHUB_TOKEN}@github.com/solarfrantz/${CIRCLE_PROJECT_REPONAME}.git .

      - run:
          name: Download resources
          command: |
            cd icons
            rm -f *
            git checkout package.json
            
            wget -q ${ICOMOON_URL}/selection-svg.json
            
            #TODO check if any files are modified in order to abort the next steps
            git status --porcelain
            GIT_CHANGES=`git status --porcelain --untracked-files=no | wc -l`
            if [ $GIT_CHANGES -eq 0 ] ; then
                echo "No icon changes"
            else
                echo "Found $GIT_CHANGES changes"
                echo "export GIT_CHANGES=GIT_CHANGES" >> $BASH_ENV
                source $BASH_ENV
                
                npm version patch
                git add .
            fi

      - run:
          name: npm pack & publish
          command: |
            echo "Found $GIT_CHANGES changes"
            exit 0
            cd icons
            npm pack

            # authenticate with npmjs token
            echo "//registry.npmjs.org/:_authToken=${NPMJS_TOKEN}" > .npmrc
            
            # npm login --registry=https://npm.pkg.github.com
            npm publish

      - deploy:
          name: Trigger deployment
          command: |
            echo "Found $GIT_CHANGES changes"
            exit 0

            git config credential.helper 'cache --timeout=120'
            git config user.email "francisc.ungureanu@solarwinds.com"
            git config user.name "solarfrantz"
            git commit -m "Trigger deployment"
            # Push quietly to prevent showing the token in log
            # git push -q https://${DOCS_GITHUB_TOKEN}@github.com/solarfrantz/${CIRCLE_PROJECT_REPONAME}.git ${CIRCLE_BRANCH}
