version: 2
jobs:
  build:
    context: nova-assets
    machine: true
    steps:
      - run:
          name: Clone repo
          working_directory: ~/workdir
          command: |
            echo "HERE1"
            echo $DOCS_GITHUB_TOKEN
            echo "HERE2"
            echo ${DOCS_GITHUB_TOKEN}
            git clone --depth 1 https://${DOCS_GITHUB_TOKEN}@github.com/solarfrantz/test1.git
      - run:
          name: Download resources
          working_directory: ~/workdir/test1
          command: wget https://i.icomoon.io/public/temp/a976e5f24b/UntitledProject/selection-svg.json
      - deploy:
          name: Trigger docs deployment
          working_directory: ~/workdir/test1
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "francisc.ungureanu@solarwinds.com"
            git config user.name "solarfrantz"
            git commit --allow-empty -m "Trigger deployment"
            # Push quietly to prevent showing the token in log
            git push -q https://${DOCS_GITHUB_TOKEN}@github.com/solarfrantz/test1.git main
