version: 2
jobs:
  build:
    context: nova-assets
    machine: true
    steps:
      - run:
          name: Clone repository
          working_directory: ~/workdir
          command: |
            pwd
            git clone https://${DOCS_GITHUB_TOKEN}@github.com/solarfrantz/${CIRCLE_PROJECT_REPONAME}.git
            ls -al
      - run:
          name: Download resources
          working_directory: ~/workdir/${CIRCLE_PROJECT_REPONAME}
          command: |
            pwd
            wget -q https://i.icomoon.io/public/temp/a976e5f24b/UntitledProject/selection-svg.json
            ls -al
      - deploy:
          name: Trigger deployment
          working_directory: ~/workdir/${CIRCLE_PROJECT_REPONAME}
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "francisc.ungureanu@solarwinds.com"
            git config user.name "solarfrantz"
            git commit --allow-empty -am "Trigger deployment"
            # Push quietly to prevent showing the token in log
            git push -q https://${DOCS_GITHUB_TOKEN}@github.com/solarfrantz/${CIRCLE_PROJECT_REPONAME}.git ${CIRCLE_BRANCH}
