version: 2
jobs:
  build:
    machine: true
    steps:
      - run:
          name: Clone docs
          working_directory: ~/workdir
          command: |
            git clone --depth 1 https://github.com/solarfrantz/test1
      - run:
          name: Download resources
          command: wget https://i.icomoon.io/public/temp/a976e5f24b/UntitledProject/selection-svg.json
      - deploy:
          name: Trigger docs deployment
          working_directory: ~/workdir/docs
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "sample@user.com"
            git config user.name "SampleUser"
            git commit --allow-empty -m "Trigger deployment"
            # Push quietly to prevent showing the token in log
            git push -q https://github.com/solarfrantz/test1 main
